### ISSUE TITLE
Toggle mute status does not `unmute` muted microphones.

### ISSUE THREAD

**Issue by rafek1241** [aderusha/BoseQCMicMute#1] opened 2021-12-22 11:57 UTC
**issue:**  Toggle mute status does not `unmute` muted microphones.
![image](https://user-images.githubusercontent.com/9272027/147089293-bbec4e2c-eb33-41e6-b824-95eb89b00f66.png)

**Comment by aderusha** [comment] 2021-12-22 13:26
Can you explain a little more about your setup?  Which devices are being muted/unmuted and which aren't?

**Comment by rafek1241** [comment] 2021-12-22 20:12
Sure, I'm using qc35II and windows 10. When I clicked toggle mute status, it muted microphones but not fully. My friend on teams said that my voice was interrupted but still not fully muted. When I selected manually to unmute all microphones, it wasn't fixed. I didn't use buttons from headphones In this case.

**Comment by aderusha** [comment] 2021-12-23 13:45
Closing this issue as a duplicate of [#2](https://github.com/aderusha/BoseQCMicMute/issues/2)

**Closed as completed by aderusha** 2021-12-23 13:45 UTC
